name: "Dev: Test & Deploy"

on:
  push:
    branches: [dev]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - run: yarn test

  build_and_deploy:
    name: Build & deploy
    runs-on: ubuntu-latest
    needs: [tests]
    env:
      MONGODB_CONN_STRING: ${{ secrets.MONGODB_CONN_STRING_DEV }}
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/setup-node@v2
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn build
      - run: yarn deploy --stage dev

